import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import InstallBootstrap from "./Components/InstallBootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mayank Tiwari",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  

  return (
    <html lang="en">
      <body className={inter.className}>
        <InstallBootstrap/>
        {children}</body>
    </html>
  );
}
